- name: Install firefox
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Installiere helper packages
  ansible.builtin.apt:
    name:
      - wget
      - bsd-mailx

- name: "Create /etc/firefox dir"
  ansible.builtin.file:
    path: /etc/firefox
    mode: "0755"
    state: directory
    owner: root
    group: root

- name: Set Firefox sysprefs.js
  ansible.builtin.template:
    src: sysprefs.js
    dest: /etc/firefox/syspref.js
    mode: "0644"

- name: Copy firefox extension update cron script
  ansible.builtin.template:
    src: firefox-extension-update.sh
    dest: /etc/cron.daily/firefox-extension-update.sh
    mode: "0755"
  notify: Run firefox extension update

- name: Create symbolic links for extensions
  ansible.builtin.file:
    src: "/usr/local/share/ansible_downloads/{{ item.name }}"
    dest: "/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{{ item.id }}"
    state: link
    force: true
  with_items: "{{ firefox_extensions }}"
